Design-teardown
rida-elbahtouri/Design-Teardown pull request #1
Opened 2020-05-20 14:32 UTC by Dipeshtwis

This project includes :-

- used flexbox in the header section
- used grid to group all the elements on the Smashing homepage.
- used background colors of divs with different shades of gray which correspond to their visual weight on the Smashing homepage.
- use fonts from google font

2020-05-20 19:28 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-05-20 20:00 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi **TEAM**, you did really great in building this project :+1: However, to improve our code and make it even better, let us address the comments below:
- ```Nav```, the nav items uses div to position the elements
![ccp](https://user-images.githubusercontent.com/46388113/82489171-b6dc7e00-9ad0-11ea-8f6c-21011f25074d.png)
- Kindly apply the DRY rule to our CSS file, we have some repeating properties, let us fix it. Let us use this [article](https://www.linkedin.com/in/daniel-larbi-addo/) as a guide
- Let us implement the float property in positioning some of our elements
![wa](https://user-images.githubusercontent.com/46388113/82491399-20aa5700-9ad4-11ea-964f-193f45998d8c.png)
- Let us use article tag where appropriate
![wa1](https://user-images.githubusercontent.com/46388113/82491601-60713e80-9ad4-11ea-8469-fb4ac9736f1b.png)

Kindly fix these changes and submit another code review :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-05-20 20:00 UTC, addod19 commented on index.html
> +        <div class="header-author first-sec">
Kindly use ```<article> instead of <div class="header-author first-sec">```

2020-05-21 10:46 UTC, rida-elbahtouri commented
**we added these changes to our project :**

the nav items use div to position the elements
apply the DRY rule to our CSS file
implement the float property  
use article tag

2020-05-21 21:49 UTC, bolah2009 approved these changes
It's a 👍🏾 from me!

### :heavy_check_mark: Approved!

Awesome job making the suggested changes. :relaxed: 

Good luck with your next projects. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2020-05-22 06:32 UTC, Dipeshtwis commented on index.html
> +        <div class="header-author first-sec">
We used the article wherever requires.
Thank you for your suggestion.

2020-05-22 06:32 UTC, merged